Download junit xml files from MH
Android and raspi emit junit xml files that MH pulls from the devices and uploads to GCS.
Download those files and upload them as artifacts so the test report uploader will pick them up.

diff --git a/.github/actions/on_device_tests/action.yaml b/.github/actions/on_device_tests/action.yaml
--- a/.github/actions/on_device_tests/action.yaml
+++ b/.github/actions/on_device_tests/action.yaml
@@ -100,3 +100,25 @@ runs:
           --change_id "${GITHUB_SHA}" \
           watch ${{ env.SESSION_ID }}
       shell: bash
+    - name: Download ${{ matrix.platform }} Test Results
+      shell: bash
+      env:
+        GCS_PATH: gs://cobalt-unittest-storage/results
+      run: |
+        set -eux
+        gsutil -d cp "${GCS_PATH}/${SESSION_ID}.zip" .
+        if [[ $? -ne 0 ]]; then
+          warn="Unable to download results from ${GCS_PATH}/${SESSION_ID}.zip"
+          echo "::warning title=No unit test results::$warn"
+          exit 0
+        fi
+
+        mkdir -p unit-test-results/${{ matrix.platform }}/${{ matrix.shard }}/
+        unzip ${SESSION_ID}.zip -d unit-test-results/${{ matrix.platform }}/${{ matrix.shard }}/
+    - name: Archive Unit Test Results
+      uses: actions/upload-artifact@v3
+      # TODO: Should only run for unit-tests
+      if: always()
+      with:
+        name: unit-test-results
+        path: unit-test-results/
